"""created muscles model

Revision ID: 62605caf8ac5
Revises: 5dd0a81669c7
Create Date: 2022-12-08 12:31:07.721419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62605caf8ac5'
down_revision = '5dd0a81669c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muscles')
    # ### end Alembic commands ###
